fenneclab/hugo-bin

README.md, lib/binary.js, package.json
I misunderstood `pkg-conf` and did not test enough.
=> fix(default): deprecate hugoVersion configuration

package.json
=> Backport 71c224c

README.md
This updates the readme to reflect latest Hugo version and the next increment of the NPM publish.
=> Update to latest Hugo version

package.json
Hugo latest is at .26 as of Aug 7th. This change updates the latest Hugo version.
=> Update Hugo version to latest

README.md, package.json
=> feat(hugo): upgrade Hugo to v0.30.2

README.md, package.json
=> feat(hugo): upgrade Hugo to v0.31

README.md, package.json
=> feat(hugo): upgrade Hugo to v0.32.4

README.md, package.json
=> feat(hugo): upgrade Hugo to v0.33

README.md, package.json
See https://gohugo.io/news/0.35-relnotes/
=> feat(hugo): upgrade Hugo to v0.35

package.json
=> feat(hugo): upgrade Hugo to v0.40.2

lib/index.js, package-lock.json, package.json
See [Hugo release 0.41](https://github.com/gohugoio/hugo/releases/tag/v0.41). Adds privacy features for GDPR.
=> feat(hugo): upgrade Hugo to v0.41.0 (#53)

package.json
=> feat(hugo): upgrade Hugo to v0.42.1

lib/install.js, package-lock.json, package.json
close: #45
Thank you so much for [your help](https://github.com/fenneclab/hugo-bin/pull/62) @XhmikosR
=> chore(*): upgrade bin-wrapper

package-lock.json, package.json
=> Minor package.json tweaks

cli.js, lib/install.js, test/index.js
=> Minor lint tweaks.

package-lock.json, package.json
@satoshun00: I don't like that you squashed my previous patch. I'd like to fix it but it'll need force pushing the master branch...
Anyway, here's another small patch. Makes the dependency tree smaller.
=> Switch to rimraf for deleting the folder.

lib/install.js, package-lock.json, package.json
=>  Replace logalot with signale and tweak installation messages

lib/index.js
=> Remove unneeded condition.

package.json
=> feat(hugo): upgrade Hugo to v0.44

package.json
=> feat(hugo): upgrade Hugo to v0.45.1

package.json
=> feat(hugo): upgrade Hugo to v0.46

package.json
=> feat(hugo): upgrade Hugo to v0.48

package.json
=> feat(hugo): upgrade Hugo to v0.49.2

package.json
https://github.com/gohugoio/hugo/releases/tag/v0.50
=> feat(hugo): upgrade Hugo to v0.50

package.json
https://github.com/gohugoio/hugo/releases/tag/v0.51
=> feat(hugo): upgrade Hugo to v0.51

package.json
https://gohugo.io/news/0.53-relnotes/
=> feat(hugo): upgrade Hugo to v0.53

.travis.yml, package-lock.json, package.json
There's also a new Hugo version to be published, so I will wait for that too.
=> Update deps and disable Travis notifications

package.json
https://github.com/fenneclab/hugo-bin/issues/92
=> Update Hugo to 0.55.2

.github/FUNDING.yml, package.json
@satoshun00 I hope you are OK with this, if not let me know :)
=> Add funding information

.github/workflows/ci.yml, lib/install.js, package-lock.json, package.json
=> Remove rimraf dependency

README.md, lib/index.js, test/options.test.js
=> Allow setting hugo version via env

.github/workflows/ci.yml
Waiting for an npm fix for Windows
TODO:
=> CI: add Node.js 22

.github/workflows/ci.yml, lib/index.js
Can be enabled with the `NODE_DEBUG=hugo-bin` environment variable
=> Add basic debugging via `NODE_DEBUG=hugo-bin`
